import { test, expect } from './fixtures';

test.describe('reports', () => {
  test('hub lists both report types', async ({ page }) => {
    await page.goto('/reports');
    await expect(page.getByRole('heading', { name: 'Reports' })).toBeVisible();
    await expect(page.getByText('Income & Expense')).toBeVisible();
    await expect(page.getByText('Expense Log')).toBeVisible();
  });

  test('opens the income & expense report', async ({ page }) => {
    await page.goto('/reports');
    await page.getByRole('button', { name: 'Open report' }).first().click();
    await expect(page).toHaveURL(/\/reports\/income-expense$/);
    // Computed 6-month summary drives this page.
    await expect(page.getByRole('main').getByText(/Revenue|Expense/i).first()).toBeVisible();
  });

  test('opens the expense log report', async ({ page }) => {
    await page.goto('/reports/expense-log');
    await expect(page.getByRole('main').getByText(/Expense/i).first()).toBeVisible();
    // Seeded expenses surface their supplier/category.
    await expect(page.getByText(/Joe Plumber|Maintenance|Electricity/i).first()).toBeVisible();
  });

  // The preview and the PDF are generated by completely separate code, so these assert the
  // shape they are supposed to share. If someone changes one layout and not the other, the
  // preview stops being a preview.
  test('income preview groups by owner and shows a net per property', async ({ page }) => {
    await page.goto('/reports/income-expense');

    await expect(page.getByText(/^Owner:/).first()).toBeVisible({ timeout: 10_000 });
    // Each property is a Revenue / Expenses / Net trio, not two separate bands.
    const block = page.locator('div').filter({ hasText: /^123 Main St$/ }).first();
    await expect(block).toBeVisible();
    for (const label of ['Revenue', 'Expenses', 'Net']) {
      await expect(page.getByText(label, { exact: true }).first()).toBeVisible();
    }
    await expect(page.getByText('Owner total (net)').first()).toBeVisible();
  });

  test('expense log preview shows the property-by-category pivot', async ({ page }) => {
    await page.goto('/reports/expense-log');

    await expect(page.getByText('Summary by category & property')).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(/^Owner:/).first()).toBeVisible();
    // A property row, and the column totals underneath it.
    await expect(page.getByText(/123 Main St,/).first()).toBeVisible();
    await expect(page.getByText('Total', { exact: true }).first()).toBeVisible();
  });
});

/**
 * Revenue recognition basis.
 *
 * Chosen per report rather than stored on the account, which is the whole point: a stored
 * preference would silently re-interpret history, so the same year's report would say two
 * different things depending on when it was generated.
 */
test.describe('revenue recognition basis', () => {
  test('both options are offered on the income & expense report', async ({ page }) => {
    await page.goto('/reports/income-expense');
    await expect(page.getByRole('button', { name: 'Accrual', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Cash', exact: true })).toBeVisible();
  });

  test('accrual is pre-selected for an Israeli account', async ({ page }) => {
    // The country config pre-selects; it never forces. Israel files on accrual, so nothing
    // changes for an existing user opening this page.
    await page.goto('/reports/income-expense');
    await expect(page.getByRole('button', { name: 'Accrual', exact: true })).toHaveAttribute(
      'aria-pressed',
      'true',
    );
  });

  test('the basis reaches the server when a report is generated', async ({ page }) => {
    await page.goto('/reports/income-expense');
    await page.getByRole('button', { name: 'Cash', exact: true }).click();

    const request = page.waitForRequest((r) => r.url().includes('/reports/income-expense?'));
    await page.getByRole('button', { name: /^PDF/ }).click();
    const url = (await request).url();
    expect(url).toContain('basis=cash');
  });

  test('the expense log has no basis control', async ({ page }) => {
    // Nothing to recognise: expenses already count on the date they were paid under both.
    await page.goto('/reports/expense-log');
    await expect(page.getByRole('button', { name: 'Accrual', exact: true })).toHaveCount(0);
  });
});
