import { test, expect } from './fixtures';

test.describe('reports', () => {
  test('hub lists both report types', async ({ page }) => {
    await page.goto('/reports');
    await expect(page.getByRole('heading', { name: 'Reports' })).toBeVisible();
    await expect(page.getByText('Income & Expense')).toBeVisible();
    await expect(page.getByText('Expense Log')).toBeVisible();
  });

  test('opens the income & expense report', async ({ page }) => {
    await page.goto('/reports');
    await page.getByRole('button', { name: 'Open report' }).first().click();
    await expect(page).toHaveURL(/\/reports\/income-expense$/);
    // Computed 6-month summary drives this page.
    await expect(page.getByRole('main').getByText(/Revenue|Expense/i).first()).toBeVisible();
  });

  test('opens the expense log report', async ({ page }) => {
    await page.goto('/reports/expense-log');
    await expect(page.getByRole('main').getByText(/Expense/i).first()).toBeVisible();
    // Seeded expenses surface their supplier/category.
    await expect(page.getByText(/Joe Plumber|Maintenance|Electricity/i).first()).toBeVisible();
  });

  // The preview and the PDF are generated by completely separate code, so these assert the
  // shape they are supposed to share. If someone changes one layout and not the other, the
  // preview stops being a preview.
  test('income preview groups by owner and shows a net per property', async ({ page }) => {
    await page.goto('/reports/income-expense');

    await expect(page.getByText(/^Owner:/).first()).toBeVisible({ timeout: 10_000 });
    // Each property is a Revenue / Expenses / Net trio, not two separate bands.
    const block = page.locator('div').filter({ hasText: /^123 Main St$/ }).first();
    await expect(block).toBeVisible();
    for (const label of ['Revenue', 'Expenses', 'Net']) {
      await expect(page.getByText(label, { exact: true }).first()).toBeVisible();
    }
    await expect(page.getByText('Owner total (net)').first()).toBeVisible();
  });

  test('expense log preview shows the property-by-category pivot', async ({ page }) => {
    await page.goto('/reports/expense-log');

    await expect(page.getByText('Summary by category & property')).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(/^Owner:/).first()).toBeVisible();
    // A property row, and the column totals underneath it.
    await expect(page.getByText(/123 Main St,/).first()).toBeVisible();
    await expect(page.getByText('Total', { exact: true }).first()).toBeVisible();
  });
});
